### ISSUE TITLE
How to get ahoy email to work with Mongoid?

### ISSUE THREAD

**Issue by ericraio** [ankane/ahoy_email#41] opened 2015-12-17 19:44 UTC
I really want to use ahoy_email, this is perfect for what I need but I don't use ActiveRecord but instead I use Mongoid. Any options on what I can do?

**Comment by sunny** [comment] 2016-03-10 16:46
Duplicate of #10.

**Comment by ankane** [comment] 2016-07-25 06:06
Happy to accept a PR for this.

**Comment by ankane** [comment] 2018-05-01 02:45
Closing as dup of #10

**Closed by ankane** 2018-05-01 02:45 UTC
Labels: enhancement
